import type { Trip, TripContent } from "@/types/trip";

/** Blank trip used to seed the "nuevo viaje" form. */
export const EMPTY_TRIP: Trip = {
  id: "",
  slug: "",
  title: "",
  title_2: "",
  top_subtitle: "",
  destiny: "",
  coaching_subtitle: "",
  date_month: "",
  date_days: "",
  date_month_2: "",
  date_days_2: "",
  header_image: "",
  header_mobile_image: "",
  header_video: "",
  price_promo: 0,
  price_final: 0,
  price_promo_message: "",
  price_final_message: "",
  price_promo_deposit_message: "Reserva con 50%",
  price_final_deposit_message: "Reserva con 50%",
  price_promo_title: "Promo",
  price_final_title: "Precio Final",
  section_1_title: "",
  section_1_description: "",
  section_1_subdescription: "",
  section_1_image: "",
  section_2_title: "",
  section_2_description: "",
  section_2_image: "",
  section_video_title: "",
  section_video_description: "",
  section_video_url: "",
  final_img_1: "",
  final_img_2: "",
  order: 0,
  created_at: "",
  updated_at: "",
};

export const EMPTY_CONTENT: TripContent = {
  title: "",
  subtitle: "",
  description: "",
  subtitle_2: "",
  description_2: "",
  image_url: "",
  images: [],
};
