export type TripContent = {
  id?: string;
  title: string;
  subtitle?: string;
  description: string;
  subtitle_2?: string;
  description_2?: string;
  image_url: string;
  trip_id?: string;
  order?: number;
};

export type Trip = {
  id: string;
  slug: string;
  title: string;
  title_2?: string;
  top_subtitle?: string;
  destiny: string;
  coaching_subtitle: string;
  date_month: string;
  date_days: string;
  date_month_2?: string;
  date_days_2?: string;
  header_image: string;
  header_mobile_image?: string;
  header_video?: string;
  price_promo: number;
  price_final: number;
  price_promo_message: string;
  price_final_message: string;
  section_1_title: string;
  section_1_description: string;
  section_1_subdescription: string;
  section_1_image: string;
  section_2_title: string;
  section_2_description: string;
  section_2_image: string;
  section_video_title: string;
  section_video_description: string;
  section_video_url: string;
  final_img_1: string;
  final_img_2: string;
  order: number;
  trip_contents?: TripContent[];
  is_deleted?: boolean;
  created_at: string;
  updated_at: string;
};
